### ISSUE TITLE
Information about the corresponding article.

### ISSUE THREAD

**Issue by SaqibMamoon** [LearningKeqi/RethinkingBCA#1]
Thank you for sharing such a clean, comprehensive and great effort. 

I would like to ask is there any corresponding article to this repository, as i searched and couldn't find any article. If there is please let us know it would be available if hasn't already.

Thanks a lot.

**Comment by LearningKeqi** [comment]
Hi,

Thanks for your interests in our work, this work is currently under review. We’ll make sure to update the repository and notify the community as soon as it becomes available.

Thanks.

**Comment by LearningKeqi** [comment]
> Thank you for sharing such a clean, comprehensive and great effort.
> 
> I would like to ask is there any corresponding article to this repository, as i searched and couldn't find any article. If there is please let us know it would be available if hasn't already.
> 
> Thanks a lot.


Hi!

We have submitted our paper to arXiv, please kindly refer to: https://arxiv.org/abs/2501.17207 for more details of our work.
Thanks for your interest!.

**Comment by SaqibMamoon** [comment]
@LearningKeqi  Thanks a lot!
